### ISSUE TITLE
Update dependency versions and use Project.toml

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaGraphs/GraphIO.jl#27]
It would be cool if the project dependency versions could be updated. When I installed GraphIO.jl, I got some large downgrades:

![image](https://user-images.githubusercontent.com/8310743/80521212-49658380-8950-11ea-93d0-443775bf8023.png)

**Comment by sbromberger** [comment]
There is no Project.toml right now. That's something we need to fix.

**Comment by simonschoelly** [comment]
We seem to have a Project.toml now, so I am closing this.
