### ISSUE TITLE
UndefVarError: DOT not defined

### ISSUE THREAD

**Issue by pauljurczak** [JuliaGraphs/GraphIO.jl#34]
I'm trying to test basic functionality and I got stuck here:
```
julia> using LightGraphs, GraphIO

julia> graph = loadgraph("gr.dot", "gr", DOTFormat())
ERROR: UndefVarError: DOT not defined
Stacktrace:
 [1] DOTFormat() at /home/paul/.julia/packages/GraphIO/IgxnP/src/deprecations.jl:29
 [2] top-level scope at REPL[3]:1
 [3] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```
I'm using Julia 1.5.1 on Ubuntu 18.04.

**Comment by simonschoelly** [comment]
Some graph formats need additional packages - we did not want to make them mandatory for that package to reduce unnecessary dependencies, so  you have to import them manually. I thought we had documented this in the README but apparently that is not the case.

In your case you need to install `ParserCombinator` and then write `using ParserCombinator`, then the dot format should be available.

**Comment by pauljurczak** [comment]
Thank you, it works now. One more question, if I may: I thought that graph name is optional, but skipping it doesn't work:
```
julia> graph = loadgraph("gr.dot", DOTFormat())
ERROR: Graph graph not found
......
julia> graph = loadgraph("gr.dot", format=DOTFormat())
ERROR: MethodError: no method matching loadgraph(::String; format=GraphIO.DOT.DOTFormat())
```
Am I reading https://juliagraphs.org/LightGraphs.jl/stable/persistence/#LightGraphs.loadgraphs-Tuple{AbstractString,LightGraphs.AbstractGraphFormat} wrong?

**Comment by simonschoelly** [comment]
The methods for importing dot are defined here: https://github.com/JuliaGraphs/GraphIO.jl/blob/eb35fe30fca6c438cc3814ae24f8d8e54b85c182/src/DOT/Dot.jl#L86, looks like the signature there is slightly different.

**Comment by pauljurczak** [comment]
So the documentation is not accurate, right?

**Comment by pauljurczak** [comment]
Never mind. This error:
```
julia> graph = loadgraph("gr.dot", DOTFormat())
ERROR: Graph graph not found
```
was caused by graph name different from `"graph"`.

**Comment by yonkeltron** [comment]
Is there any way to make this clear from the error message?

**Comment by sbulcsu** [comment]
Same here:
`ERROR: Graph graph not found`
I had to check what is the name of the graph in the .graphml file and use that one:
`<graph id="G" edgedefault="directed">`
as
`g = loadgraph("test.graphml", "G", GraphMLFormat())`

This should be added to the Documentation/README.md and/or to the error message!
